# Generated by Django 4.2.7 on 2026-04-03 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationmembership',
            options={'ordering': ['-joined_at']},
        ),
    ]
