# Generated by Django 4.2.7 on 2026-04-04 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discovery', '0002_nearbydevice_organization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nearbydevice',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='nearbydevice',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_device', to=settings.AUTH_USER_MODEL),
        ),
    ]
